<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $weblink = $option_value->getObject(); ?>

<div class="form_content">
    <div id="list" class="edit_page weblink weblink_mono">
        <div class="mono">
            <form id="weblinkForm" name="weblinkForm" method="post" action="<?php echo $this->getUrl('weblink/application_mono/editpost') ?>" class="form-horizontal">
                <h3 class="title-editor no-border-radius">
                    <?php echo $this->_('Information') ?>
                </h3>
                <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
                <div class="container-fluid first-row-feature">
                    <div class="infos">
                        <div id="weblink_content">
                            <div class="form-group">
                                <div class="col-sm-2">
                                    <label for="link"><?php echo $this->_('Link:') ?></label>
                                </div>
                                <div class="col-sm-8">
                                    <input type="text" id="weblink" name="link" class="input-flat url" value="<?php echo $weblink->getLink()->getUrl() ?>"/>
                                </div>

                                <!-- champ de recuperation de la valeur "withpanel" de la base de donnée -->
                                <input type="hidden" name="withpanel" value="<?php echo $weblink->getLink()->getwithpanel();?>" id="testCheck">

                                <!-- champ checkbox pour " Add a panel navigation " -->
                                <div class="col-sm-4 col-sm-offset-2">
                                    <input type="checkbox"  id="checked"/> <b>Add a panel navigation</b>
                                </div>


                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="save pull-right">
                                <button class="btn btn-block color-blue" type="submit">
                                    <?php echo $this->_('Save'); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">


    // ici on teste si checkbox prend comme valeur 1 ou 0 et ajouter cette derniere dans le input type hidden
    $(function(){

        $('#checked').change(function () {
            if ($('#checked').is(':checked')) {

                $('#testCheck').val(1);

            }else{
                $('#testCheck').val(0);
            }

        })

    });


    // au chargement du DOM en teste le input type hidden ( valeur reçu de la base de donnée )
    $(function(){

        if ($('#testCheck').val() == '1') {

            $("#checked").prop("checked", true);

        }

    });


    page.setCallback('didappear', function() {

        $('#weblink').change(function() {
            if(!$(this).val().isEmpty() && !$(this).val().startsWith('http://') && !$(this).val().startsWith('https://')) {
                $(this).val('http://'+$(this).val());
            }
        });
        $('#weblinkForm').submit(function() {
            if(!$(this).valid()) return false;
            reload(this, this.action, true, function(datas) {
                if(datas.success) {
                    iframe.f.reloadTabbar();




                }
            });
            return false;
        });

    });

    page.setCallback('willdisappear', function() {
        $('#weblink').unbind('change');
        $('#weblinkForm').unbind('submit');
    });

</script>